import docx

doc = docx.Document("tabla.docx")
for fila in doc.tables[0].rows:
    for celda in fila.cells:
        pass
        #print(celda.text, end=" ")
    #print()

cont="""SANDUCHE PAPAS-FRITAS PAPAS-FRITAS POLLO-FRITO PAPAS-FRITAS HAMBURGUESA 
PIZZA HAMBURGUESA SANDUCHE POLLO-FRITO HOT-DOG HAMBURGUESA 
PIZZA HOT-DOG PAPAS-FRITAS SANDUCHE SANDUCHE PIZZA 
HOT-DOG HAMBURGUESA PIZZA PAPAS-FRITAS SANDUCHE PAPAS-FRITAS 
SANDUCHE SANDUCHE POLLO-FRITO SANDUCHE POLLO-FRITO PAPAS-FRITAS 
SANDUCHE SANDUCHE HOT-DOG SANDUCHE PAPAS-FRITAS HAMBURGUESA 
SANDUCHE HAMBURGUESA PIZZA POLLO-FRITO SANDUCHE PIZZA 
PIZZA HOT-DOG HOT-DOG HOT-DOG SANDUCHE PIZZA 
SANDUCHE HAMBURGUESA PIZZA PIZZA HOT-DOG HOT-DOG 
SANDUCHE POLLO-FRITO HOT-DOG PAPAS-FRITAS POLLO-FRITO HAMBURGUESA 
HAMBURGUESA POLLO-FRITO HOT-DOG PAPAS-FRITAS PAPAS-FRITAS PAPAS-FRITAS 
HOT-DOG HAMBURGUESA HAMBURGUESA PAPAS-FRITAS POLLO-FRITO HAMBURGUESA 
SANDUCHE POLLO-FRITO POLLO-FRITO SANDUCHE PIZZA PIZZA 
HOT-DOG POLLO-FRITO HOT-DOG PAPAS-FRITAS PAPAS-FRITAS SANDUCHE 
SANDUCHE SANDUCHE HAMBURGUESA PAPAS-FRITAS HAMBURGUESA POLLO-FRITO 
HOT-DOG PAPAS-FRITAS HAMBURGUESA HOT-DOG PIZZA HOT-DOG"""
c = cont.split()
general = len(c)
hot_dog=c.count("HOT-DOG")
sanduche = c.count("SANDUCHE")
pizza = c.count("PIZZA")
hamburguesa = c.count("HAMBURGUESA")
papas_fritas = c.count("PAPAS-FRITAS")
pollo_frito = c.count("POLLO-FRITO")
print(f"""hay {general} elementos , {hot_dog} hot-dog, {sanduche} sanduche, {pizza} pizza, {hamburguesa} hamburguesa, {papas_fritas} papas fritas y {pollo_frito} pollo frito y en \n
total hay {hot_dog + sanduche + pizza + hamburguesa + papas_fritas + pollo_frito} elementos""")